### ISSUE TITLE
How about KD between two heterogeneous backbone?

### ISSUE THREAD

**Issue by lihao0374** [CVMI-Lab/SparseKD#1]
Good work. Have you tried to perform KD between Voxels and Pillars?

**Comment by jihanyang** [comment]
Yes, but we only have some basic attemptations. It can also obtain some improvements.

**Comment by lihao0374** [comment]
Nice, do you have any plan to write a paper/tech-report on this topic?

**Comment by jihanyang** [comment]
No, we don't have such plan nowadays.
