### ISSUE TITLE
No waymo_processed_data_v0_5_0_waymo_dbinfos_train_sampled_1_global.pkl error reported

### ISSUE THREAD

**Issue by PleasantPhoenix** [CVMI-Lab/SparseKD#10]
Hello, there is no waymo displayed when training_ processed_ data_ v0_ 5_ 0_ waymo_ dbinfos_ train_ sampled_ 1_ The global.pkl file, but the processing of waymo data does not generate waymo_ processed_ data_ v0_ 5_ 0_ waymo_ dbinfos_ train_ sampled_ 1_ Global.pkl file, only waymo_ processed_ data_ v0_ 5_ 0_ waymo_ dbinfos_ train_ sampled_ 1. pkl file, how do I handle this situation?

**Comment by jihanyang** [comment]
Hello, have you created the gt database and data infos as the getting start shows?

**Comment by PleasantPhoenix** [comment]
Yes,I have created.Two of the files I generated are similar to the file name I was looking for in the error, with a different suffix being waymo_ processed_ data_ v0_ 5_ 0_ gt_ database_ train_ sampled_ 1_ Global.npy, where the word 'global' is missing from the name, is waymo_ processed_ data_ v0_ 5_ 0_ waymo_ dbinfos_ train_ sampled_ 1.pkl.And as shown in the following figure, the file for getting start does not say that the file required in the error will be generated.
<img width="686" alt="1679817993593" src="https://user-images.githubusercontent.com/86542147/227763352-a89b5c5e-2ea7-48e8-9e3a-600973e1e621.png">

**Comment by jihanyang** [comment]
Yes. This is caused by some version change of pcdet, hope this haven't annoyed you a lot.

**Comment by PleasantPhoenix** [comment]
Thank you for your reply. May I ask you if I will_ processed_  data_  v0_  5_  0_  waymo_  dbinfos_  train_  sampled_  1. Change the pkl file name to waymo_ processed_ data_ v0_ 5_ 0_ waymo_ dbinfos_ train_ sampled_ 1_ Global.pkl solves this problem. Is this approach feasible?

**Comment by jihanyang** [comment]
Yes, this is actually the best solution.
