### ISSUE TITLE
I fixed the bug when using cp-voxel-xs_sparsekd.yaml

### ISSUE THREAD

**Issue by JianyyuWang** [CVMI-Lab/SparseKD#13]
When using spconv2.x, you enter this code causing an error.

in pcdet/utils/kd_utils/kd_tgi_utils.py:
def _narrow_weight(k, curr_v, self_model_state, spconv_keys):
    # adapt spconv weights from version 1.x to version 2.x if you used weights from spconv 1.x
    # a little bug
    # if k in spconv_keys and self_model_state[k].shape[0:3] != curr_v.shape[0:3]
    if k in spconv_keys and self_model_state[k].shape[1:3] != curr_v.shape[1:3]:
        # (k1, k2, k3, c_in, c_out) to (c_out, k1, k2, k3, c_in)
        curr_v = curr_v.permute(4, 0, 1, 2, 3)

    for d in range(len(self_model_state[k].shape)):
        curr_v = curr_v.narrow(d, 0, self_model_state[k].shape[d])

    return curr_v

“if k in spconv_keys and self_model_state[k].shape[0:3] != curr_v.shape[0:3]” need to be changed to “if k in spconv_keys and self_model_state[k].shape[1:3] != curr_v.shape[1:3]:”

**Comment by jihanyang** [comment]
Thanks for your information! This would be helpful for others meet this questions.
