### ISSUE TITLE
Waymo dataset evaluation issue

### ISSUE THREAD

**Issue by SimonSongg** [CVMI-Lab/SparseKD#14]
Hi, thanks for your great work. I have some issue in the evaluation of my model. I used the Waymo Open Dataset and followed the steps to process it and trained a centerpoint model. But when I tested it, the inference was good, the predicted results were collected, but the calculation for AP and APH got wrong, this process seemed to run on CPU (CPU load to 100%), tensorflow used all of my GPU memory and got Illegal instruction or segment fault. 

I used RTX 4070 Ti Super, CUDA 11.8, waymo-open-dataset-tf-2-12-0 and tensorflow 2.12.0.

Any suggestion are appreciated! Thanks!
![image](https://github.com/CVMI-Lab/SparseKD/assets/70959938/9722ae63-9f28-47fb-bc9c-86d3e45ff4c7)

**Comment by SimonSongg** [comment]
If I reduced the test samples, it worked. But that does not make sense.

**Comment by jihanyang** [comment]
I haven't met this before. It might be better to raise this issue in the github repo of waymo-open-dataset
