### ISSUE TITLE
Flops calculation

### ISSUE THREAD

**Issue by SimonSongg** [CVMI-Lab/SparseKD#15]
Hi,

I followed your instruction in GETTING_STARTED.md to replace the conv.py in spconv package. But I got error: `AttributeError: 'SparseConvTensor' object has no attribute 'flops'`

Do we also need to modify SparseConvTensor class in core.py as well?

Thanks!

**Comment by SimonSongg** [comment]
I added an attribute in SparseConvTensor class, and it works.

**Comment by jihanyang** [comment]
Cool!
