### ISSUE TITLE
Waymo dataset 20% train and val imagesets txt file

### ISSUE THREAD

**Issue by jakeju92** [CVMI-Lab/SparseKD#6]
Hi, I'm trying to reproduce the experiment result in SparseKD paper. Could you please provide the txt file of 20% train and val info which should be placed under imagesets/ folder. Thanks in advance!

**Comment by jihanyang** [comment]
Hello, existing config is already 20% train and val refer to https://github.com/CVMI-Lab/SparseKD/blob/8572093edc77d4217f7596d9e1de68c6dc77e420/tools/cfgs/dataset_configs/waymo_dataset.yaml#L12-L15

This is the default implementation of OpenPCDet.

**Comment by jakeju92** [comment]
Cool
