### ISSUE TITLE
Why the original CP-Voxel is more efficient than CP-Pillar?

### ISSUE THREAD

**Issue by jakeju92** [CVMI-Lab/SparseKD#7]
Hi,

It's very counterintuitive that the original CP-Voxel model achieves better performance as well as less flops and memory than the CP-Pillar model which makes pillar-based method looks like useless. The pillar-based models should be more efficient than voxel-based models since 3D sparse conv operations have higher computational cost according to my emprical experience. Apart from what you explained in the paper that CP-Pillar has more layers in BEV encoder part, are there any other reasons that you design two types of models like this. Have you try to make modules after PFE layer all the same for both pillar& voxel-based model. So, it would be a fair comparison for both pillar-based and voxel-based method although it is not the main focus of your paper.

**Comment by jihanyang** [comment]
I recommand you to read the appendix about the inference time analysis first if you haven't read before. That part should answer some of your questions here.

**Comment by jakeju92** [comment]
Cool! That's exactly what I'm looking for, thx!
